language: python
addons:
  sauce_connect: true
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq poppler-data poppler-utils python-dev python-imaging python-setuptools python-pdftools python-lxml
  - sudo pip install simplejson
install:
  - pip install -r requirements.txt --timeout 30
# command to run tests, e.g. python setup.py test
script:
  - ./manage.py test
  # for the browser tests we need a real db with full data
  - wget http://oknesset-devdb.s3.amazonaws.com/dev.db.bz2
  - bunzip2 dev.db.bz2
  - ./manage.py migrate
  - ./manage.py test --testrunner=knesset.browser_test_runner.Runner --browser=Sauce --full-initialization
